### ISSUE TITLE
exceeds tier max size on pre-commit.ci

### ISSUE THREAD

**Issue by nijel** [biomejs/pre-commit#16]
When trying to upgrade to 0.6.0 it fails on pre-commit-ci with:

```
build of https://github.com/biomejs/pre-commit:@biomejs/biome@1.9.4@v0.6.0 for node@lts exceeds tier max size 250MiB: 387.2MiB
```

CI job: https://results.pre-commit.ci/run/github/3559019/1733506687.PLbe5uftRdWVoGqQuC1Zog

I have no clue whether it is something to be addressed here (maybe caused by https://github.com/biomejs/pre-commit/pull/12), at biome or at pre-commit.ci.

**Comment by flying-sheep** [comment]
Oof, this makes the weekly pre-commit autoupdate for all of my projects useless. Please revert.
