### ISSUE TITLE
Executable `biome` not found

### ISSUE THREAD

**Issue by tyilo** [biomejs/pre-commit#6]
My pre-commit hook recently stopped working. I have tried changing the version of pre-commit, this hook and biome, but it still seems to happen.

Steps to reproduce:

```
$ docker run --rm -it python:alpine sh
# apk add git libstdc++
# pip install pipx
# cd /tmp
# mkdir test
# cd test
# git init
# touch a.js
# git add a.js
# cat > .pre-commit-config.yaml
repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: v0.4.0
    hooks:
      - id: biome-check
        additional_dependencies:
          - "@biomejs/biome@1.8.3"
^D
# pipx run pre-commit run --show-diff-on-failure --color=always --all-files
biome check..............................................................Failed
- hook id: biome-check
- exit code: 1

Executable `biome` not found
```

**Comment by tyilo** [comment]
Seems to be a problem with pre-commit itself (or npm): https://github.com/pre-commit/pre-commit/issues/3261

**Comment by ematipico** [comment]
I am going to close it, this is an issue with Node.js 22.5.0. Revert to 22.4.1 until they release a patch. Context: https://github.com/nodejs/node/pull/53934
